### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by xlafter** [AlexMachin1997/Shopping-List-Assistant#3]
Hey, just to let you know this app when compiling produces errors.

**Comment by AlexMachin1997** [comment]
Thank's for letting me know.

How did you even find this application 😆 

This was done as part of my university project a few years ago, it's not been updated since. Plus I now use Expo instead of barebones react native apps.

Just out of curioisty what errors did you get ?

**Comment by AlexMachin1997** [comment]
@xlafter I rebuilt the app using Expo instead over [here](https://github.com/AlexMachin1997/Shopping-List-Assistant-With-Expo)

I'm just about finished rewriting it to use hooks, I'll be merging the changes any day now.
